name: Script Static Analysis
on:
  push:
    paths: 
      - '**.sh'
  pull_request:
    paths:
      - '**.sh'
jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get update
      - run: sudo apt-get install shellcheck
      - uses: actions/checkout@v2
      - run: shellcheck setup.sh install.sh
